### ISSUE TITLE
"can't access lexical declaration 'topic' before initialization"

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki-plugin-frame#21]
Changes in 5ead2f94909b3376ea504d007ef563877943e818, removing `let {name, topic, sourceData} = data` before the switch statement causes problems in the "requestSourceData" case which fails with `can't access lexical declaration 'topic' before initialization`.

Discovered on http://contract.relocalizecreativity.net/view/welcome-visitors/view/aspects-of-contract

**Comment by dobbs** [comment]
Just published `v0.10.3` with a fix for this bug.

Sadly, I also left a permanent record that I don't actually know how to use github's references in a commit: c7e0087f08c04427e701cf53c946974c445809c4
For my future self "fix #2" wanted to be "fix #21"

Thanks again, @SamAxe, for the PR.

**Comment by dobbs** [comment]
We've published a new docker image with this update so the fix can be confirmed at relocalizecreativity.net
https://hub.docker.com/layers/dobbs/farm/1.0.27/
